import './globals.css'
import Menu from "@/app/Menu";

export const metadata = {
    title: 'Hello',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">

        <body>
        <Menu/>
        {children}
        </body>
        </html>
    )
}
